from dataclasses import dataclass

from stock_scorer.backtesting import BacktestRequest, BacktestSummary, run_backtest
from stock_scorer.research_store import (
    StrategyVersion,
    get_active_strategy,
    initialize_research_store,
    insert_evolution_candidate,
    insert_strategy_version,
    open_research_connection,
)


@dataclass(frozen=True)
class EvolutionRequest:
    tickers: list[str]
    training_start_date: str
    training_end_date: str
    validation_start_date: str
    validation_end_date: str
    initial_cash: float = 10_000.0


@dataclass(frozen=True)
class EvolutionResult:
    candidate_strategy_id: int | None
    training_run_id: int | None
    validation_run_id: int | None
    active_validation_return: float
    validation_total_return: float
    max_drawdown: float
    message: str


def evolve_strategy(request: EvolutionRequest) -> EvolutionResult:
    initialize_research_store()
    with open_research_connection() as connection:
        active = get_active_strategy(connection)

    active_validation = run_backtest(
        BacktestRequest(
            tickers=request.tickers,
            start_date=request.validation_start_date,
            end_date=request.validation_end_date,
            initial_cash=request.initial_cash,
        ),
        strategy=active,
    )
    best_strategy = active
    best_training: BacktestSummary | None = None
    best_validation: BacktestSummary | None = None
    best_score = _objective(active_validation)

    for candidate in _candidate_grid(active):
        training = run_backtest(
            BacktestRequest(
                tickers=request.tickers,
                start_date=request.training_start_date,
                end_date=request.training_end_date,
                initial_cash=request.initial_cash,
            ),
            strategy=candidate,
        )
        validation = run_backtest(
            BacktestRequest(
                tickers=request.tickers,
                start_date=request.validation_start_date,
                end_date=request.validation_end_date,
                initial_cash=request.initial_cash,
            ),
            strategy=candidate,
        )
        score = _objective(validation)
        if training.metrics.total_return >= 0 and score >= best_score:
            best_strategy = candidate
            best_training = training
            best_validation = validation
            best_score = score

    if best_validation is None or best_training is None:
        return EvolutionResult(
            candidate_strategy_id=None,
            training_run_id=None,
            validation_run_id=None,
            active_validation_return=active_validation.metrics.total_return,
            validation_total_return=active_validation.metrics.total_return,
            max_drawdown=active_validation.metrics.max_drawdown,
            message="No validation-improving candidate found.",
        )

    with open_research_connection() as connection:
        stored_candidate = insert_strategy_version(
            connection,
            name="candidate-evolved",
            status="candidate",
            medium_entry_threshold=best_strategy.medium_entry_threshold,
            short_entry_threshold=best_strategy.short_entry_threshold,
            stop_loss_pct=best_strategy.stop_loss_pct,
            take_profit_pct=best_strategy.take_profit_pct,
            max_holding_days=best_strategy.max_holding_days,
            position_size_pct=best_strategy.position_size_pct,
            notes="Generated by conservative grid evolution.",
        )
        insert_evolution_candidate(
            connection,
            strategy_id=stored_candidate.strategy_id,
            training_run_id=best_training.run_id,
            validation_run_id=best_validation.run_id,
            active_validation_return=active_validation.metrics.total_return,
            candidate_validation_return=best_validation.metrics.total_return,
            max_drawdown=best_validation.metrics.max_drawdown,
        )

    return EvolutionResult(
        candidate_strategy_id=stored_candidate.strategy_id,
        training_run_id=best_training.run_id,
        validation_run_id=best_validation.run_id,
        active_validation_return=active_validation.metrics.total_return,
        validation_total_return=best_validation.metrics.total_return,
        max_drawdown=best_validation.metrics.max_drawdown,
        message="Candidate strategy generated.",
    )


def _candidate_grid(active: StrategyVersion) -> list[StrategyVersion]:
    candidates: list[StrategyVersion] = []
    for medium_delta in (-5, 0):
        for short_delta in (-5, 0):
            for take_profit in (active.take_profit_pct, min(0.30, active.take_profit_pct + 0.04)):
                candidates.append(
                    StrategyVersion(
                        strategy_id=active.strategy_id,
                        name="candidate",
                        status="candidate",
                        medium_entry_threshold=max(50, active.medium_entry_threshold + medium_delta),
                        short_entry_threshold=max(45, active.short_entry_threshold + short_delta),
                        stop_loss_pct=active.stop_loss_pct,
                        take_profit_pct=take_profit,
                        max_holding_days=active.max_holding_days,
                        position_size_pct=active.position_size_pct,
                        created_at=active.created_at,
                        notes="candidate",
                    )
                )
    return candidates


def _objective(summary: BacktestSummary) -> float:
    return summary.metrics.total_return - summary.metrics.max_drawdown * 0.5

